### PR TITLE
fix: cannot input issue title when new issue buffer is already exists #71

### PR DESCRIPTION
**Pull request by yoshio15**
#71
added deletion of `gh://:owner/:repo/:branch/issues/new` buffer just after creating new issue.
by this fix, I could confirm that this issue doesn't happen no more.

### CODE REVIEW

**Comment by skanehira** [comment]
Thanks.
If create new issue as following order, we don't need to delete buffer and can reuse issue template fast.

1. open new issue buffer
2. get issue template
3. select template
4. input title
4. edit issue body

So, we just change order of creating issues.

**Comment by yoshio15** [comment]
thank you for your reply.

hmm i see..., I didn't take into consideration using issue template.
I'll keep on working on this issue and I'm going to fix it.

**Comment by yoshio15** [comment]
@skanehira 
I updated PR as shown below.
- changed order of input issue title from first to just after a issue-template is selected
- fix to delete buffer(s:gh_issues_new_bufid) after inputting title only when the repository doesn't have any issue-templates, so that you can repeat creating new issue over and over again

**Review by skanehira — APPROVED** [review]
Thanks!
LGTM

**Pull request merged**
